cache_path: .licenses

sources:
  bundler: false
  rubygems: false
  npm: false
  pip: false
  go: false
  maven: false
  gradle: false
  composer: false

allowed:
  - apache-2.0
  - bsd-2-clause
  - bsd-3-clause
  - cc0-1.0
  - epl-1.0
  - epl-2.0
  - gpl-2.0
  - gpl-3.0
  - isc
  - lgpl-2.1
  - lgpl-3.0
  - mit
  - mpl-2.0
  - unlicense
  - zlib

apps:
  - name: dotfiles
    source_path: .
