tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
cask "docker"
cask "firefox"
cask "google-chrome"
cask "notion"
cask "slack"
cask "visual-studio-code"
cask "zoom"
cask "karabiner-elements"
mas "Kindle", id: 405399194
mas "LINE", id: 539883307

# tap "adoptopenjdk/openjdk"
# brew "bash-completion"
# brew "carthage"
# brew "cmark"
# brew "cocoapods"
# brew "coreutils"
# brew "google-java-format"
# brew "gradle"
# brew "jenv"
# brew "libpq"
# brew "node"
# brew "nodebrew"
# brew "nvm"
# brew "openjdk@11"
# brew "zsh-completions"
# cask "oracle-jdk"