tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/cask-drivers"
brew "mas"
brew "zsh-completions"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
# brewでgitをインストールする事により
# zsh-completion用のgitの設定ファイルを/usr/local/share/zsh/site-functions以下に置く
# https://www.setoya-blog.com/entry/2020/06/11/115558
brew "git"
brew "trash-cli"
brew "unzip"
cask "docker"
cask "firefox"
cask "microsoft-edge"
cask "karabiner-elements"
cask "microsoft-auto-update"
cask "microsoft-office"
cask "notion"
cask "slack"
cask "visual-studio-code"
cask "zoom"
cask "vlc"
cask "deepl"
# .appファイルのインストールのため、手動でインストールすること
# cask "logi-options-plus"
cask "elgato-stream-deck"
cask "intellij-idea"
cask "dbeaver-community"
cask "tableplus"
cask "webstorm"
cask "obsidian"
cask "alfred"
cask "discord"
cask "evernote"
cask "dropbox"
cask "cheatsheet"
cask "kindle"
cask "tweeten"
cask "google-japanese-ime"
mas "LINE", id: 539883307
mas "Yoink", id: 457622435

# クライアント開発
brew "volta"
brew "uv"
# Google Cloud CLI
cask "google-cloud-sdk"
# tap "adoptopenjdk/openjdk"
# brew "carthage"
# brew "cmark"
# brew "cocoapods"
# brew "coreutils"
# brew "google-java-format"
# brew "gradle"
# brew "jenv"
# brew "libpq"
# brew "node"
# brew "nodebrew"
# brew "nvm"
# brew "openjdk@11"
# 
# cask "oracle-jdk"